[build]
dockerfile = "./Dockerfile"

[deploy]
startCommand = "dotnet AttendanceAPI.dll"

[[services]]
type = "web"
name = "api"
port = 8080

[env]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
ASPNETCORE_URLS = "http://0.0.0.0:8080"
